version: "3.0"
services:
  app:
    container_name: ${PROJECT_NAME}-app-dev
    image: ${PROJECT_NAME}_app-dev:latest
    volumes:
      - ../:/root/${PROJECT_NAME}/
      - venv:/root/${PROJECT_NAME}/.venv/
      - jupyter-config:/root/.jupyter/
      - ~/.ssh/:/root/.ssh/:ro
    ports:
      - ${port:-8888}:8888
volumes:
  venv:
  jupyter-config:
